apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: temp-rule
spec:
  ## Used by services inside the Kubernetes cluster
  destination:
    name: temp
  route:
  - labels:
      version: v1
    weight: 90
  - labels:
      version: v2
    weight: 10

